FROM ghcr.io/tauffer-consulting/domino-base-piece:latest

# Install specific requirements
RUN apt-get -y update
RUN apt-get install -y ffmpeg

# Need to copy pieces source code
COPY config.toml domino/pieces_repository/
COPY pieces domino/pieces_repository/pieces
COPY .domino domino/pieces_repository/.domino

# Install specific python dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
    openai==0.27.8 \
    pydub==0.25.1 \
    tiktoken==0.4.0 \
    langchain[llms]==0.0.330