FROM ghcr.io/tauffer-consulting/domino-airflow-pod:latest

# Install specific requirements
RUN apt-get -y update
RUN apt-get install -y ffmpeg

# Need to copy pieces source code
COPY config.toml domino/pieces_repository/
COPY pieces domino/pieces_repository/pieces
COPY .domino domino/pieces_repository/.domino

# Install specific python dependencies
RUN pip install openai==0.27.4
RUN pip install pydub==0.25.1
RUN pip install tiktoken==0.3.3