FROM ghcr.io/tauffer-consulting/domino-base-piece:gpu

# Install specific requirements
ENV TZ=UTC
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install ffmpeg -y

# Need to copy operators source code
COPY config.toml domino/pieces_repository/
COPY pieces domino/pieces_repository/pieces
COPY .domino domino/pieces_repository/.domino

# Install specific python dependencies
RUN pip install transformers==4.34.1

# Dowload transformers model
RUN python -c "import huggingface_hub; huggingface_hub.snapshot_download('facebook/bart-large-cnn')"