FROM ghcr.io/tauffer-consulting/domino-base-piece:gpu


# Install specific requirements
ENV TZ=UTC
ARG DEBIAN_FRONTEND=noninteractive
RUN apt update
RUN apt install ffmpeg -y
RUN apt install git -y

# Need to copy operators source code
COPY config.toml domino/pieces_repository/
COPY pieces domino/pieces_repository/pieces
COPY .domino domino/pieces_repository/.domino

# Install specific python dependencies
RUN pip install -U openai-whisper==20231106

# Dowload Whisper model
RUN python3 -c "import whisper; whisper.load_model('tiny')"