# TODO update to :latest
FROM ghcr.io/tauffer-consulting/domino-base-piece:latest-dev

# Install specific requirements
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ca-certificates \
    cmake \
    build-essential \
    gcc \
    g++

RUN apt-get install -y ffmpeg

# Need to copy pieces source code
COPY config.toml domino/pieces_repository/
COPY pieces domino/pieces_repository/pieces
COPY .domino domino/pieces_repository/.domino

# Install specific python dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir \
    openai==0.27.8 \
    pydub==0.25.1 \
    tiktoken==0.4.0 \
    langchain[llms]==0.0.330